# Generated by Django 4.0 on 2021-12-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Random_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assets/img/category/')),
                ('clicks_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Random_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='assets/img/detail/')),
                ('website', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('sharing_number', models.IntegerField()),
                ('change_number', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_category.random_category')),
            ],
        ),
    ]
